model:
  model_name: microsoft/resnet-50
  task_type: classification
  num_classes: 1000
  pretrained: true
  dropout: 0.2
  mixup_alpha: 0.2
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler: cosine
  scheduler_params:
    T_max: 100
    eta_min: 1e-6
  epochs: 100
data:
  train_data_path: /Volumes/<catalog>/<schema>/<volume>/<path>/data/train
  val_data_path: /Volumes/<catalog>/<schema>/<volume>/<path>/data/val
  test_data_path: /Volumes/<catalog>/<schema>/<volume>/<path>/data/test
  batch_size: 32
  num_workers: 4
  model_name: microsoft/resnet-50
  image_size:
  - 224
  - 224
  normalize_mean:
  - 0.485
  - 0.456
  - 0.406
  normalize_std:
  - 0.229
  - 0.224
  - 0.225
  augment: true
  augmentations:
    horizontal_flip: true
    vertical_flip: false
    rotation: 15
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_crop: true
    random_resize:
    - 0.8
    - 1.2
training:
  max_epochs: 100
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler: cosine
  scheduler_params:
    T_max: 100
    eta_min: 1e-6
  early_stopping_patience: 10
  monitor_metric: val_loss
  monitor_mode: min
  checkpoint_dir: /Volumes/<catalog>/<schema>/<volume>/<path>/checkpoints/classification
  save_top_k: 3
  log_every_n_steps: 50
  distributed: true
  use_ray: false
  use_serverless_gpu: true
  use_gpu: true
  resources_per_worker:
    CPU: 2
    GPU: 1
  serverless_gpu_type: A10
  serverless_gpu_count: 4
  volume_checkpoint_dir: /Volumes/<catalog>/<schema>/<volume>/<path>/volume_checkpoints/classification
  num_workers: 1
  master_port: null
  preferred_strategy: null
  preferred_devices: null
mlflow:
  experiment_name: /Users/<your.email@databricks.com>/cv_classification_resnet
  run_name: resnet50
  log_model: true
  tags:
    framework: lightning
    model: resnet
    dataset: imagenet
output:
  results_dir: /Volumes/<catalog>/<schema>/<volume>/<path>/results/classification
  save_predictions: true
  visualization:
    save_images: true
    max_images: 10
