# Model Configuration
model:
  name: "resnet50"
  pretrained: true
  num_classes: 1000
  dropout: 0.2

# Training Configuration
training:
  batch_size: 32
  num_workers: 4
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "cosine"
  warmup_epochs: 5

# Data Configuration
data:
  train_path: "/dbfs/datasets/imagenet/train"
  val_path: "/dbfs/datasets/imagenet/val"
  image_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Augmentation Configuration
augmentation:
  horizontal_flip: true
  vertical_flip: false
  rotation: 15
  brightness_contrast: 0.2
  random_crop: true
  random_erasing: true

# Distributed Training
distributed:
  backend: "ray"
  num_workers: 4
  use_gpu: true
  strategy: "ddp"

# MLflow Configuration
mlflow:
  experiment_name: "classification_resnet50"
  tracking_uri: "databricks"
  registry_uri: "databricks-uc"
  model_name: "resnet50_classifier"
  tags:
    task: "classification"
    model: "resnet50"
    dataset: "imagenet"

# Logging Configuration
logging:
  log_every_n_steps: 50
  save_top_k: 3
  monitor: "val_loss"
  mode: "min" 