# Model Configuration
model:
  # Model architecture
  model_name: "facebook/detr-resnet-50"
  num_classes: 80  # COCO classes
  pretrained: true
  
  # Training hyperparameters
  learning_rate: 0.0004
  weight_decay: 0.0004
  scheduler: "cosine"
  scheduler_params:
    T_max: 100
    eta_min: 0.00006
  epochs: 5
  
  # Task-specific settings
  task_type: "detection"
  class_names: null  # Will be loaded from COCO annotations
  
  # Detection-specific settings
  confidence_threshold: 0.5
  iou_threshold: 0.5
  max_detections: 100

# Training Configuration
training:
  # Batch and optimization settings
  batch_size: 16
  num_workers: 4
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1
  
  # Early stopping and checkpointing
  early_stopping_patience: 10
  checkpoint_dir: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/checkpoints/"
  save_top_k: 3
  monitor: "val_loss"
  mode: "min"
  
  # Logging settings
  log_every_n_steps: 50
  log_metrics: true
  log_artifacts: true
  
  # Ray distributed training settings
  distributed: false
  use_gpu: true
  resources_per_worker:
    CPU: 2
    GPU: 1

# Data Configuration
data:
  # Dataset paths
  train_path: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/val2017/"
  val_path: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/val2017/"
  test_path: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/val2017/"
  annotation_file: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/instances_val2017.json"
  
  # Data processing
  image_size: [800, 800]  # DETR default size
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
  # Data loading
  augment: true
  num_workers: 4
  pin_memory: true
  
  # Augmentation settings
  augmentations:
    horizontal_flip: true
    vertical_flip: false
    rotation: 15
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_crop: true
    random_resize: [0.8, 1.2]