# Model Configuration
model:
  # Model architecture
  model_name: "nvidia/mit-b0"
  num_classes: 19  # Cityscapes classes
  pretrained: true
  
  # Training hyperparameters
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler: "cosine"
  scheduler_params:
    T_max: 100
    eta_min: 1e-6
  epochs: 100
  
  # Task-specific settings
  task_type: "segmentation"
  class_names: null  # Will be loaded from dataset
  segmentation_type: "semantic"
  
  # Segmentation-specific settings
  aux_loss_weight: 0.4
  mask_threshold: 0.5

# Training Configuration
training:
  # Batch and optimization settings
  batch_size: 16  # Smaller batch size for segmentation
  num_workers: 4
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 2  # Gradient accumulation for larger effective batch size
  
  # Early stopping and checkpointing
  early_stopping_patience: 10
  checkpoint_dir: "/Volumes/users/aradhya_chouhan/coco_mini-train/checkpoints"
  save_top_k: 3
  monitor: "val_loss"
  mode: "min"
  
  # Logging settings
  log_every_n_steps: 50
  log_metrics: true
  log_artifacts: true
  
  # Ray distributed training settings
  distributed: false
  use_gpu: true
  resources_per_worker:
    CPU: 2
    GPU: 1

# Data Configuration
data:
  # Separate paths for train/val/test splits
  train_data_path: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/train"
  train_annotation_file: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/annotations_train.json"
  val_data_path: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/val"
  val_annotation_file: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/annotations_val.json"
  test_data_path: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/test"
  test_annotation_file: "/Volumes/users/aradhya_chouhan/coco_mini-train/data/annotations_test.json"
  
  # Data processing
  image_size: [512, 512]  # Common size for segmentation
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
  # Data loading
  augment: true
  num_workers: 4
  pin_memory: true
  
  # Augmentation settings
  augmentations:
    horizontal_flip: true
    vertical_flip: false
    rotation: 15
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_crop: true
    random_resize: [0.8, 1.2]