# Model Configuration
model:
  model_name: "facebook/mask2former-swin-base-coco-panoptic"
  task_type: "universal_segmentation"
  num_classes: 133  # COCO panoptic has 133 classes (80 things + 53 stuff)
  pretrained: true
  
  # Segmentation-specific settings
  segmentation_type: "panoptic"
  aux_loss_weight: 0.4
  mask_threshold: 0.5
  
  # Training hyperparameters
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler: "cosine"
  scheduler_params:
    T_max: 300
    eta_min: 1e-6
  epochs: 300

# Data Configuration
data:
  # Dataset paths
  train_data_path: "/Volumes/<catalog>/<schema>/<volume>/<path>/data/train2017/"
  train_annotation_file: "/Volumes/<catalog>/<schema>/<volume>/<path>/data/panoptic_train2017.json"
  val_data_path: "/Volumes/<catalog>/<schema>/<volume>/<path>/data/val2017/"
  val_annotation_file: "/Volumes/<catalog>/<schema>/<volume>/<path>/data/panoptic_val2017.json"
  test_data_path: "/Volumes/<catalog>/<schema>/<volume>/<path>/data/test2017/"
  test_annotation_file: "/Volumes/<catalog>/<schema>/<volume>/<path>/data/panoptic_test2017.json"
  
  # Data loading parameters
  batch_size: 8
  num_workers: 4
  model_name: "facebook/mask2former-swin-base-coco-panoptic"  # For adapter initialization
  
  # Image processing
  image_size: [800, 800]
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
  # Augmentation
  augment: true
  augmentations:
    horizontal_flip: true
    vertical_flip: false
    rotation: 10
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_crop: true
    random_resize: [0.8, 1.2]

# Training Configuration
training:
  # Basic training parameters
  max_epochs: 300
  
  # Learning rate and optimization
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler: "cosine"
  scheduler_params:
    T_max: 300
    eta_min: 1e-6
  
  # Early stopping
  early_stopping_patience: 30
  monitor_metric: "val_pq"
  monitor_mode: "max"
  
  # Checkpointing
  checkpoint_dir: "/Volumes/<catalog>/<schema>/<volume>/<path>/checkpoints/universal_segmentation"
  save_top_k: 3
  
  # Logging
  log_every_n_steps: 50
  
  # Distributed training
  distributed: false
  use_ray: false  # Set to true for multi-node training with Ray
  use_gpu: true
  resources_per_worker:
    CPU: 4
    GPU: 1

# MLflow Configuration
mlflow:
  experiment_name: "universal_segmentation_training"
  run_name: "mask2former_swin_base_panoptic"
  log_model: true
  tags:
    framework: "lightning"
    model: "mask2former"
    dataset: "coco_panoptic"

# Output Configuration
output:
  results_dir: "/Volumes/<catalog>/<schema>/<volume>/<path>/results/universal_segmentation"
  save_predictions: true
  visualization:
    save_images: true
    max_images: 10 